### ISSUE TITLE
pip3 install lnet does not result in successful execution afterwards: lnet.utils unknown. ModuleNotFoundError: No module named 'lnet'

### ISSUE THREAD

**Issue by renepickhardt** [cdecker/lnet#1]
I installed lnet via pip3 with: 

```
Renes-iMacReal:hacken rpickhardt$ pip3 install lnet
Collecting lnet
  Downloading https://files.pythonhosted.org/packages/d9/da/e1bc3c6a2f6b39220544698a82711f7ceeadda7d78e3f28821bfcc7d5bcd/lnet-0.0.1-py3-none-any.whl
Installing collected packages: lnet
Successfully installed lnet-0.0.1
```

I created a file `g.dot` with the code from the example of the README.md and executed `lnet-cli` which was successfully installed. It told me a requirement was missing:

```
Renes-iMacReal:lnet rpickhardt$ lnet-cli g.dot 
Traceback (most recent call last):
  File "/usr/local/bin/lnet-cli", line 4, in <module>
    from flask_jsonrpc.proxy import ServiceProxy
ModuleNotFoundError: No module named 'flask_jsonrpc'
Renes-iMacReal:lnet rpickhardt$ pip3 flask_jsonrpc
ERROR: unknown command "flask_jsonrpc"
Renes-iMacReal:lnet rpickhardt$ pip3 install flask_jsonrpc
Collecting flask_jsonrpc
  Downloading https://files.pythonhosted.org/packages/cb/1f/e6d66e8498609ba04bac76155b2ea884df95531e93501bf4ef009d40a83c/Flask-JSONRPC-0.3.1.tar.gz (680kB)
    100% |████████████████████████████████| 686kB 3.8MB/s 
Requirement already satisfied: Flask>=0.10 in /usr/local/lib/python3.6/site-packages (from flask_jsonrpc) (1.0.2)
Requirement already satisfied: Jinja2>=2.10 in /usr/local/lib/python3.6/site-packages (from Flask>=0.10->flask_jsonrpc) (2.10)
Requirement already satisfied: itsdangerous>=0.24 in /usr/local/lib/python3.6/site-packages (from Flask>=0.10->flask_jsonrpc) (0.24)
Requirement already satisfied: Werkzeug>=0.14 in /usr/local/lib/python3.6/site-packages (from Flask>=0.10->flask_jsonrpc) (0.14.1)
Requirement already satisfied: click>=5.1 in /usr/local/lib/python3.6/site-packages (from Flask>=0.10->flask_jsonrpc) (7.0)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python3.6/site-packages (from Jinja2>=2.10->Flask>=0.10->flask_jsonrpc) (1.0)
Building wheels for collected packages: flask-jsonrpc
  Running setup.py bdist_wheel for flask-jsonrpc ... done
  Stored in directory: /Users/rpickhardt/Library/Caches/pip/wheels/20/19/ee/1997190c68e64adbf358bffe803df29fd55418616078d529bf
Successfully built flask-jsonrpc
Installing collected packages: flask-jsonrpc
Successfully installed flask-jsonrpc-0.3.1
```

however after successfully installing the requirement there was still a problem as lnet.utils was not known to my python environment. 

```
Renes-iMacReal:lnet rpickhardt$ lnet-cli g.dot 
Traceback (most recent call last):
  File "/usr/local/bin/lnet-cli", line 5, in <module>
    from lnet.utils import BitcoinD, NodeFactory
ModuleNotFoundError: No module named 'lnet'
```

seems to be an operation system problem (or I should say a problem with multiple python installations) since the following also did not work: 
```
python3.6 setup.py install
cd bin
python3.6 lnet-cli ../g.dot start
```
resulting in the same problem with flask_jsonrpc not being available.

```
Renes-iMacReal:bin rpickhardt$ python3.6 lnet-cli ../g.dot start
Traceback (most recent call last):
  File "lnet-cli", line 4, in <module>
    from flask_jsonrpc.proxy import ServiceProxy
ModuleNotFoundError: No module named 'flask_jsonrpc'
```
but pip3 shows me that flask is installed:
```
Renes-iMacReal:bin rpickhardt$ pip3 install flask_jsonrpc
Requirement already satisfied: flask_jsonrpc in /usr/local/lib/python3.6/site-packages (0.3.1)
Requirement already satisfied: Flask>=0.10 in /usr/local/lib/python3.6/site-packages (from flask_jsonrpc) (1.0.2)
Requirement already satisfied: Jinja2>=2.10 in /usr/local/lib/python3.6/site-packages (from Flask>=0.10->flask_jsonrpc) (2.10)
Requirement already satisfied: Werkzeug>=0.14 in /usr/local/lib/python3.6/site-packages (from Flask>=0.10->flask_jsonrpc) (0.14.1)
Requirement already satisfied: click>=5.1 in /usr/local/lib/python3.6/site-packages (from Flask>=0.10->flask_jsonrpc) (7.0)
Requirement already satisfied: itsdangerous>=0.24 in /usr/local/lib/python3.6/site-packages (from Flask>=0.10->flask_jsonrpc) (0.24)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python3.6/site-packages (from Jinja2>=2.10->Flask>=0.10->flask_jsonrpc) (1.0)
```
so lets check our python version:
```
Renes-iMacReal:bin rpickhardt$ python3 --version
Python 3.6.4 :: Anaconda, Inc.
```
even making sure I use the correct python3.6 version which was used to install flask_jsonrpc will just result in the fact again that lnet.utils is unknown: 

```
Renes-iMacReal:bin rpickhardt$ /usr/local/bin/python3.6 lnet-cli ../g.dot start
Traceback (most recent call last):
  File "lnet-cli", line 4, in <module>
    from lnet.utils import BitcoinD, NodeFactory
ModuleNotFoundError: No module named 'lnet'
```
sorry have to stop here right now. No time right now to fix this.

**Comment by cdecker** [comment]
Strange, it really seems `pip3` and your default `python3` binaries are pointing to different installations. Can you share the output of `which pip3` and `which python3` and which installation gets started with `/usr/bin/env python3`?

**Comment by cdecker** [comment]
Regarding the flask_jsonrpc dependncy I'll fix that right away.

**Comment by cdecker** [comment]
Fixed the dependency and uploaded a new version 0.0.2 to pypi (https://pypi.org/project/lnet/0.0.2/) doing a `pip3 install -U lnet` should get you going

**Comment by cdecker** [comment]
Turns out I utterly messed the `setup.py` file up. I fixed it now and installing from pypi should be working with version 0.0.5 :wink: 

Sorry for the delay in addressing this.
